name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set env release name
        run: export releaseName=${{ github.event.release.name }}

      - name: Set env nexus username
        run: export NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}

      - name: Set env nexus password
        run: export NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Publish
        run: ./gradlew HoodiesNetworkKmm:publish